import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :devshops_et, DevshopsEtWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: DevshopsEt.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Expect an already installed tailwind.
config :tailwind, path: System.get_env("MIX_TAILWIND_PATH")

# Expect an already installed esbuild.
config :esbuild, path: System.get_env("MIX_ESBUILD_PATH")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
